### ISSUE TITLE
Styles window is not accessible

### ISSUE THREAD

**Issue by kamransoomro84** [juliusgb/obsidian-tldraw-plugin#62]
Currently on my Macbook Pro the Styles window opens off to the side and is unusable. I also cannot move it. See example below:

![image](https://github.com/juliusgb/obsidian-tldraw-plugin/assets/4132530/3bf78684-cca5-45e1-b475-8beeeab7bf03)

I am running Mac OS Monterey 12.6.8.

**Comment by juliusgb** [comment]
Yep. It's not a MacOs issue. Rather it comes out of combining Obsidian and Tldraw.

While developing the plugin, both tools went through major upgrades. There are atleast 3 combinations that I'm tracking at https://github.com/juliusgb?query=is%3Aopen+sort%3Atitle-asc&tab=projects

That style-box problem happens when using Obsidian versions that are older than version 1: https://github.com/juliusgb/obsidian-tldraw-plugin/issues/47
